create or replace view V_TRIPS_PERSONS_CONFIRMED as
SELECT
  TRIP_ID, COUNTRY, "DATE", TRIP_NAME, PERSON_ID, NAME, SURNAME, RESERVATION_STATUS
FROM V_TRIPS_PERSONS
WHERE RESERVATION_STATUS = 'P' or RESERVATION_STATUS = 'Z'
